# renovate-python-issue
repo to reproduce issue with python:3.alpine sha256
